### ISSUE TITLE
http proxy from HTTP_PROXY env variable?

### ISSUE THREAD

**Issue by sebest** [facebookgo/httpcontrol#4]
Hello,

With the default transport we can configure http proxy using the HTTP_PROXY env variable, but it does not seem to work with httpcontrol transport?

thanx

**Comment by daaku** [comment]
You can do this by configuring a transport like such:

```go
t := &httpcontrol.Transport{
  Proxy: http.ProxyFromEnvironment,
}
```

This is how the `http.DefaultTransport` works as well: https://golang.org/pkg/net/http/#DefaultTransport
